### PR TITLE
Support for HTTPS

### PR DESCRIPTION
**Pull request by r01k**
- Added support for HTTPS.
- Optional certificate validation.
- Now defaults to connect over HTTPS with validation.

### CODE REVIEW

**Comment by r01k** [comment]
@cgarwood, any chance to take a look at this merge request? I have the dependent integration working over HTTPS.

**Comment by cgarwood** [comment]
Since Fully Kiosk Browser's remote admin is non-https by default, I think we should still default to HTTP instead of HTTPS, but otherwise looks good 👍

**Comment by r01k** [comment]
@cgarwood, defaulted to HTTP as suggested. If you merge, please let me when it is published to Pypi to submit the pull request for Fully Kiosk in HA. Thanks!

**Review by cgarwood — APPROVED** [review]

**Comment by cgarwood** [comment]
Publishing to PyPi as 0.0.12: https://github.com/cgarwood/python-fullykiosk/actions/runs/3559698634

**Pull request merged**
